### ISSUE TITLE
Bug: bentoctl build results in 'No such file or directory: '/tmp/tmp6o7052c9fsTempFS/'

### ISSUE THREAD

**Issue by wintermute-cell** [bentoml/aws-ec2-deploy#36]
## Environment
- bentoml, version 1.1.10
- bentoctl, version 0.4.0
- Docker version 19.03.2-ce, build 6a30dfca03 (also tried 24.0.7)
- Arch Linux (6.1.65-1-lts)

## Description
Following the README, and finally running `bentoctl build -b <stable_diffusion_fp32:latest>` results in the following Exception being thrown:

```
Traceback (most recent call last):
  File "/home/user/src/project/bento/venv/bin/bentoctl", line 8, in <module>
    sys.exit(bentoctl())
             ^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/bentoctl/cli/utils.py", line 92, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/bentoctl/cli/utils.py", line 57, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/bentoctl/cli/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/bentoctl/cli/__init__.py", line 316, in build
    generate_deployable_container(
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/bentoctl/docker_utils.py", line 120, in generate_deployable_container
    backend.build(**buildx_args)
  File "/home/user/src/project/bento/venv/lib/python3.11/site-packages/bentoml/_internal/container/base.py", line 186, in build
    return subprocess.check_output(commands, cwd=context_path, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6o7052c9fsTempFS/'
```

## Expected behaviour
Running `bentoctl build -b <stable_diffusion_fp32:latest>` should result in a docker image being built.

**Comment by NoyHanan** [comment]
Having the same issue, on MacOS (macbook air m2).

**Comment by TalhaRB** [comment]
Try on bentoctl 0.3.4 I was also having this error, this version solved it.
